# This file is a template, and might need editing before it works on your project.
image: golang:latest

stages:
    - test
    - examples

format:
    stage: test
    script:
      - make test

compile:
    stage: examples
    script:
      - make examples
